---
title: "malevfemale"
author: "Nick_Fox"
date: "4/26/2017"
output: html_document
---

#init

```{r}
#install.packages("tm")
#install.packages("dplyr")
#install.packages("plyr")
#install.packages("class")
#install.packages("ggplot2")

library("tm")
library("dplyr")
library("plyr")
library("class")
library("ggplot2")

#set options
options(stringsAsFactors = FALSE)

#set parameters
gender <- c("male", "female")

pathname <- "~/Dropbox/papers"

```

#clean text

```{r}

cleanCorpus <- function(corpus) {
  corpus.tmp <- tm_map(corpus, removePunctuation)
  corpus.tmp <- tm_map(corpus.tmp, stripWhitespace)
  corpus.tmp <- tm_map(corpus.tmp, tolower)
  corpus.tmp <- tm_map(corpus.tmp, removeWords, stopwords("english"))
  return(corpus.tmp)
}

```

#build term document matrix TDM
```{r}

generateTDM <- function(gend, path) {
  s.dir <- sprintf("%s/%s", path, gend)
  s.cor <- Corpus(DirSource(directory = s.dir, encoding = "UTF-8"))
  s.cor.cl <- cleanCorpus(s.cor)
  s.tdm <- TermDocumentMatrix(s.cor.cl)
  
  s.tdm <- removeSparseTerms(s.tdm, 0.7)
  result <- list(gender = gend, tdm = s.tdm)
}

tdm <- lapply(gender, generateTDM, path = pathname)

#str(tdm)

```

#attach gender
```{r}

bindGendertoTDM <- function(tdm) {
  s.mat <- t(data.matrix(tdm[["tdm"]]))
  s.df <- as.data.frame(s.mat, stringsAsFactors = FALSE)
  
  s.df <- cbind(s.df, rep(tdm[["gender"]], nrow(s.df)))
  colnames(s.df)[ncol(s.df)] <- "targetgender"
  return(s.df)
}

genderTDM <- lapply(tdm, bindGendertoTDM)

#str(genderTDM)

```

#stack TDM matricies
```{r}

tdm.stack <- do.call(rbind.fill, genderTDM)
tdm.stack[is.na(tdm.stack)] <- 0

#head(tdm.stack)

#nrow(tdm.stack)
#ncol(tdm.stack)

```

#create holdout sample - tests accuracy
```{r}

train.idx <- sample(nrow(tdm.stack), ceiling(nrow(tdm.stack) * 0.7))

test.idx <- (1:nrow(tdm.stack)) [-train.idx]

#head(test.idx)
#head(train.idx)

```

#model - KNN k nearest neighbor

```{r}

tdm.gend <- tdm.stack [, "targetgender"]
tdm.stack.nl <- tdm.stack[, !colnames(tdm.stack) %in% "targetgender"]

knn.pred <- knn(tdm.stack.nl[train.idx, ], tdm.stack.nl[test.idx, ], tdm.gend[train.idx])



```

#access accuracy
```{r}

conf.mat <- table("predictions" = knn.pred, Actual = tdm.gend[test.idx])

conf.mat

(accuracy <- sum(diag(conf.mat) / length(test.idx) * 100))


```


```{r}

tdm.stack %>%
  ggplot()


```