---
title: "malevfemale"
author: "Nick_Fox"
date: "4/26/2017"
output: html_document
---

#init

```{r}
#install.packages("tm")
#install.packages("dplyr")
#install.packages("plyr")
#install.packages("class")
#install.packages("ggplot2")
#install.packages("tidytext")
#install.packages("stringr")


library("tm")
library("dplyr")
library("plyr")
library("class")
library("ggplot2")
library("tidytext")
library("stringr")

#set options
options(stringsAsFactors = FALSE)

#set wd
setwd("/Users/Nick_Fox/Dropbox/GitHub_master/data/malevfemale")

```

```{r}

male_words1 <- readr::read_lines("male/Aragones characterization of hispanic population in health research.txt")
male_words2 <- readr::read_lines("male/Areheart 2008 When Disability Isnt Just Right- The Entrenchment of the Medic.txt")
male_words3 <- readr::read_lines("male/Baerlocher 2010 data integrity and fraud in medical research.txt")
male_words4 <- readr::read_lines("male/Bandura SCT of mass communication.txt")
male_words5 <- readr::read_lines("male/Banglawala 2015 recent randomized controlled trials in otolaryngology.txt")
male_words6 <- readr::read_lines("male/Banks 2016 questionable research practices in the field of management.txt")
male_words7 <- readr::read_lines("male/Berke 2010 alcohol retail density and demographic predictors of health.txt")
male_words8 <- readr::read_lines("male/Bernstein 2007 built environment and alcohol consumption in urban neighborhoods.txt")
male_words9 <- readr::read_lines("male/Boadi erosion of funding of NIH.txt")
male_words10 <- readr::read_lines("male/Borders 2007 variations in drinking.txt")
male_words11 <- readr::read_lines("male/Braxton 1996 personal experiences of research misconduct.txt")
male_words12 <- readr::read_lines("male/Conley ARRA stimulus.txt")
male_words13 <- readr::read_lines("male/Corona marketing.txt")
male_words14 <- readr::read_lines("male/Coughlin 2012 ethics and scientific integrity in public health and epidemeology.txt")
male_words15 <- readr::read_lines("male/Cowen 2011 An economic and rational choice approach to the autism spectrum and human neurodiversity.txt")

female_words1 <- readr::read_lines("female/Abrajano GOTV.txt")
female_words2 <- readr::read_lines("female/acevedo garcia 2002 future directions in residential segregation and health research.txt")
female_words3 <- readr::read_lines("female/Adeigbe marketing to latinos.txt")
female_words4 <- readr::read_lines("female/Akresh Segmented assimilation.txt")
female_words5 <- readr::read_lines("female/Alaniz 1998 pro drinking messages and message environments for young adults the case of alcohol industry adverstising in african american latino and native american communties.txt")
female_words6 <- readr::read_lines("female/Ashburn 2014 power and confronting prejudice.txt")
female_words7 <- readr::read_lines("female/Bakker 2012 the rules of the game called psychological science.txt")
female_words8 <- readr::read_lines("female/beals 2009 sigma management and well-being.txt")
female_words9 <- readr::read_lines("female/Bes Rastrollo 2013 financial conflicts of interest and reporting bias regarding sugar sweetened beverages.txt")
female_words10 <- readr::read_lines("female/Campbell 2009 effectiveness of limiting alcohol outlet density as a means of reducing excessive alcohol consumption.txt")
female_words11 <- readr::read_lines("female/Carroll-Scott Disentangling neighborhood contextual associations.txt")
female_words12 <- readr::read_lines("female/Cascio 2012 Neurodiversity Autism price among mothers of children with asd.txt")
female_words13 <- readr::read_lines("female/Davidson autism online.txt")
female_words14 <- readr::read_lines("female/Dawson Discrimination, stress, and acculturation.txt")
female_words15 <- readr::read_lines("female/Garcia language in washington heights.txt")

mwords1 <- tidy(male_words1)
mwords2 <- tidy(male_words2)
mwords3 <- tidy(male_words3)
mwords4 <- tidy(male_words4)
mwords5 <- tidy(male_words5)
mwords6 <- tidy(male_words6)
mwords7 <- tidy(male_words7)
mwords8 <- tidy(male_words8)
mwords9 <- tidy(male_words9)
mwords10 <- tidy(male_words10)
mwords11 <- tidy(male_words11)
mwords12 <- tidy(male_words12)
mwords13 <- tidy(male_words13)
mwords14 <- tidy(male_words14)
mwords15 <- tidy(male_words15)

fwords1 <- tidy(female_words1)
fwords2 <- tidy(female_words2)
fwords3 <- tidy(female_words3)
fwords4 <- tidy(female_words4)
fwords5 <- tidy(female_words5)
fwords6 <- tidy(female_words6)
fwords7 <- tidy(female_words7)
fwords8 <- tidy(female_words8)
fwords9 <- tidy(female_words9)
fwords10 <- tidy(female_words10)
fwords11 <- tidy(female_words11)
fwords12 <- tidy(female_words12)
fwords13 <- tidy(female_words13)
fwords14 <- tidy(female_words14)
fwords15 <- tidy(female_words15)

words_male <- dplyr::bind_rows(mwords1, mwords2, mwords3, mwords4, mwords5, mwords6, mwords7, mwords8, mwords9, mwords10, mwords11, mwords12, mwords13, mwords14, mwords15) %>% 
  mutate(gender = "male")

words_female <- dplyr::bind_rows(fwords1, fwords2, fwords3, fwords4, fwords5, fwords6, fwords7, fwords8, fwords9, fwords10, fwords11, fwords12, fwords13, fwords14, fwords15) %>% 
  mutate(gender = "female")

words <- rbind(words_male, words_female)

tidy_words <- words %>%
  unnest_tokens(word, x)

data("stop_words")
tidy_words <- tidy_words %>%
  anti_join(stop_words)

tidy_words %>% 
  dplyr::count(word, sort = TRUE)



```


```{r}

library(tidyr)
bing <- sentiments %>%
        filter(lexicon == "bing") %>%
        select(-score)


word_sentiment <- tidy_words %>%
  inner_join(bing) %>% 
  dplyr::count(word, gender, sentiment, sort = TRUE) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative)
  

word_sentiment %>%
  dplyr::group_by(gender) %>% 
  dplyr::summarize(mean_sentiment = mean(sentiment)) %>% 
  ggplot(aes(x = gender, y = mean_sentiment, colour = gender)) + geom_col() + scale_y_continuous()



```

```{r}
#turn sentiment into total word frequency
word_sentiment <- word_sentiment %>% 
  mutate(freq = abs(sentiment))

#calculate logodds of a word appearing by gender
word_ratios <- word_sentiment %>% 
  select(-negative, -positive, -sentiment) %>% 
  group_by(word) %>% 
  filter(sum(freq) > 10) %>% 
  ungroup() %>% 
  spread(gender, freq, fill = 0) %>% 
  mutate_if(is.numeric, funs((. + 1) / sum(. + 1))) %>% 
  mutate(logratio = log2(female / male)) %>% 
  arrange(desc(logratio))

word_ratios %>% 
  arrange(abs(logratio))

```



```{r}

test<- word_ratios %>% 
  mutate(abslogratio = abs(logratio)) %>% 
  group_by(logratio < 0) %>% 
  top_n(15, abslogratio) %>% 
  ungroup() %>% 
  mutate(word2 = reorder(word, logratio)) 

test %>% 
  ggplot(aes(word2, logratio, color = logratio < 0)) + geom_segment(aes(x = word2, xend = word2, y = 0, yend = logratio), size = 1.1, alpha = 0.6) + coord_flip () + geom_point(size = 3.5) + labs(x = NULL, 
         y = "Odds of word appearing",
         title = "Words appearing in female or male first-authored papers") +
    scale_color_discrete(name = "", labels = c("Female first author", "Male first author")) + scale_y_continuous(breaks = seq(-8, 8),
                       labels = c("256x", "128x", "64x", "32x", "16x", "8x", "4x", "2x", 
                                  "Same", "2x", "4x", "8x", "16x", "32x", "64x", "128x", "256x"))




```

